#ifndef _COMMANDEXEC_HPP
 #define _COMMANDEXEC_HPP

#include "../Command/Command.hpp"
#include "../../User/User.hpp"
#include <sys/types.h>
#include <iostream>

using namespace std;

// ? "1 Welcome to the Internet Relay Network <nick>!<user>@<host>"
#define SEND_RPL_WELCOME "1 Welcome to the Internet Relay Network %s!%s@%s\r\n"
// ? "2 Your host is <servername>, running version <ver>"
#define SEND_RPL_YOURHOST "2 Your host is %s, running version %s\r\n"
// ? "3 This server was created <date>"
#define SEND_RPL_CREATED "3 This server was created %s\r\n"
// ? "4 <servername> <version> <available user modes> <available channel modes>"
#define SEND_RPL_MYINFO "4 %s %s %s %s\r\n"
// ? "5 Try server <server name>, port <port number>"
#define SEND_RPL_BOUNCE "5 Try server %s, port %s\r\n"
// ? "200 Link <version & debug level> <destination> <next server> V<protocol version> <link uptime in seconds> <backstream sendq> <upstream sendq>"
#define SEND_RPL_TRACELINK "200 Link %s %s %s V%s %s %s %s\r\n"
// ? "201 Try. <class> <server>"
#define SEND_RPL_TRACECONNECTING "201 Try. %s %s\r\n"
// ? "202 H.S. <class> <server>"
#define SEND_RPL_TRACEHANDSHAKE "202 H.S. %s %s\r\n"
// ? "203 ???? <class> [<client IP address in dot form>]"
#define SEND_RPL_TRACEUNKNOWN "203 ???? %s [%s]\r\n"
// ? "204 Oper <class> <nick>"
#define SEND_RPL_TRACEOPERATOR "204 Oper %s %s\r\n"
// ? "205 User <class> <nick>"
#define SEND_RPL_TRACEUSER "205 User %s %s\r\n"
// ? "206 Serv <class> <int>S <int>C <server> <nick!user|*!*>@<host|server> V<protocol version>"
#define SEND_RPL_TRACESERVER "206 Serv %s %sS %sC %s %s@%s V%s\r\n"
// ? "207 Service <class> <name> <type> <active type>"
#define SEND_RPL_TRACESERVICE "207 Service %s %s %s %s\r\n"
// ? "208 <newtype> 0 <client name>"
#define SEND_RPL_TRACENEWTYPE "208 %s 0 %s\r\n"
// ? "209 Class <class> <count>"
#define SEND_RPL_TRACECLASS "209 Class %s %s\r\n"
// ? "210 Unused."
#define SEND_RPL_TRACERECONNECT "210 Unused.\r\n"
// ? "211 <linkname> <sendq> <sent messages> <sent Kbytes> <received messages> <received Kbytes> <time open>"
#define SEND_RPL_STATSLINKINFO "211 %s %s %s %s %s %s %s\r\n"
// ? "212 <command> <count> <byte count> <remote count>"
#define SEND_RPL_STATSCOMMANDS "212 %s %s %s %s\r\n"
// ? "219 <stats letter> :End of STATS report"
#define SEND_RPL_ENDOFSTATS "219 %s :End of STATS report\r\n"
// ? "221 <user mode string>"
#define SEND_RPL_UMODEIS "221 %s\r\n"
// ? "234 <name> <server> <mask> <type> <hopcount> <info>"
#define SEND_RPL_SERVLIST "234 %s %s %s %s %s %s\r\n"
// ? "235 <mask> <type> :End of service listing"
#define SEND_RPL_SERVLISTEND "235 %s %s :End of service listing\r\n"
// ? "242 :Server Up %d days %d:%02d:%02d"
#define SEND_RPL_STATSUPTIME "242 :Server Up %d days %d:%02d:%02d\r\n"
// ? "243 O <hostmask> * <name>"
#define SEND_RPL_STATSOLINE "243 O %s * %s\r\n"
// ? "251 :There are <integer> users and <integer> services on <integer> servers"
#define SEND_RPL_LUSERCLIENT "251 :There are %s users and %s services on %s servers\r\n"
// ? "252 <integer> :operator(s) online"
#define SEND_RPL_LUSEROP "252 %s :operator(s) online\r\n"
// ? "253 <integer> :unknown connection(s)"
#define SEND_RPL_LUSERUNKNOWN "253 %s :unknown connection(s)\r\n"
// ? "254 <integer> :channels formed"
#define SEND_RPL_LUSERCHANNELS "254 %s :channels formed\r\n"
// ? "255 :I have <integer> clients and <integer> servers"
#define SEND_RPL_LUSERME "255 :I have %s clients and %s servers\r\n"
// ? "256 <server> :Administrative info"
#define SEND_RPL_ADMINME "256 %s :Administrative info\r\n"
// ? "257 :<admin info>"
#define SEND_RPL_ADMINLOC1 "257 :%s\r\n"
// ? "258 :<admin info>"
#define SEND_RPL_ADMINLOC2 "258 :%s\r\n"
// ? "259 :<admin info>"
#define SEND_RPL_ADMINEMAIL "259 :%s\r\n"
// ? "261 File <logfile> <debug level>"
#define SEND_RPL_TRACELOG "261 File %s %s\r\n"
// ? "262 <server name> <version & debug level> :End of TRACE"
#define SEND_RPL_TRACEEND "262 %s %s :End of TRACE\r\n"
// ? "263 <command> :Please wait a while and try again."
#define SEND_RPL_TRYAGAIN "263 %s :Please wait a while and try again.\r\n"
// ? "301 <nick> :<away message>"
#define SEND_RPL_AWAY "301 %s :%s\r\n"
// ? "302 :*1<reply> *( " " <reply> )"
#define SEND_RPL_USERHOST "302 :*1%s *( " " %s )\r\n"
// ? "303 :*1<nick> *( " " <nick> )"
#define SEND_RPL_ISON "303 :*1%s *( " " %s )\r\n"
// ? "305 :You are no longer marked as being away"
#define SEND_RPL_UNAWAY "305 :You are no longer marked as being away\r\n"
// ? "306 :You have been marked as being away"
#define SEND_RPL_NOWAWAY "306 :You have been marked as being away\r\n"
// ? "311 <nick> <user> <host> * :<real name>"
#define SEND_RPL_WHOISUSER "311 %s %s %s * :%s\r\n"
// ? "312 <nick> <server> :<server info>"
#define SEND_RPL_WHOISSERVER "312 %s %s :%s\r\n"
// ? "313 <nick> :is an IRC operator"
#define SEND_RPL_WHOISOPERATOR "313 %s :is an IRC operator\r\n"
// ? "314 <nick> <user> <host> * :<real name>"
#define SEND_RPL_WHOWASUSER "314 %s %s %s * :%s\r\n"
// ? "315 <name> :End of WHO list"
#define SEND_RPL_ENDOFWHO "315 %s :End of WHO list\r\n"
// ? "317 <nick> <integer> :seconds idle"
#define SEND_RPL_WHOISIDLE "317 %s %s :seconds idle\r\n"
// ? "318 <nick> :End of WHOIS list"
#define SEND_RPL_ENDOFWHOIS "318 %s :End of WHOIS list\r\n"
// ? "319 <nick> :*( ( \"@\" / \"+\" ) <channel> " " )"
#define SEND_RPL_WHOISCHANNELS "319 %s :*( ( \"@\" / \"+\" ) %s " " )\r\n"
// ? "321 Obsolete."
#define SEND_RPL_LISTSTART "321 Obsolete.\r\n"
// ? "322 <channel> <# visible> :<topic>"
#define SEND_RPL_LIST "322 %s %s :%s\r\n"
// ? "323 :End of LIST"
#define SEND_RPL_LISTEND "323 :End of LIST\r\n"
// ? "324 <channel> <mode> <mode params>"
#define SEND_RPL_CHANNELMODEIS "324 %s %s %s\r\n"
// ? "325 <channel> <nickname>"
#define SEND_RPL_UNIQOPIS "325 %s %s\r\n"
// ? "331 <channel> :No topic is set"
#define SEND_RPL_NOTOPIC "331 %s :No topic is set\r\n"
// ? "332 <channel> :<topic>"
#define SEND_RPL_TOPIC "332 %s :%s\r\n"
// ? "341 <channel> <nick>"
#define SEND_RPL_INVITING "341 %s %s\r\n"
// ? "342 <user> :Summoning user to IRC"
#define SEND_RPL_SUMMONING "342 %s :Summoning user to IRC\r\n"
// ? "346 <channel> <invitemask>"
#define SEND_RPL_INVITELIST "346 %s %s\r\n"
// ? "347 <channel> :End of channel invite list"
#define SEND_RPL_ENDOFINVITELIST "347 %s :End of channel invite list\r\n"
// ? "348 <channel> <exceptionmask>"
#define SEND_RPL_EXCEPTLIST "348 %s %s\r\n"
// ? "349 <channel> :End of channel exception list"
#define SEND_RPL_ENDOFEXCEPTLIST "349 %s :End of channel exception list\r\n"
// ? "351 <version>.<debuglevel> <server> :<comments>"
#define SEND_RPL_VERSION "351 %s.%s %s :%s\r\n"
// ? "352 <channel> <user> <host> <server> <nick> ( \"H\" / \"G\" > [\"*\"] [ ( \"@\" / \"+\" ) ] :<hopcount> <real name>"
#define SEND_RPL_WHOREPLY "352 %s %s %s %s %s ( \"H\" / \"G\" > [\"*\"] [ ( \"@\" / \"+\" ) ] :%s %s\r\n"
// ? "353 ( \"=\" / \"*\" / \"@\" ) <channel> :[ \"@\" / \"+\" ] <nick> *( \" \" [ \"@\" / \"+\" ] <nick> )"
#define SEND_RPL_NAMREPLY "353 ( \"=\" / \"*\" / \"@\" ) %s :[ \"@\" / \"+\" ] %s *( \" \" [ \"@\" / \"+\" ] %s )\r\n"
// ? "364 <mask> <server> :<hopcount> <server info>"
#define SEND_RPL_LINKS "364 %s %s :%s %s\r\n"
// ? "365 <mask> :End of LINKS list"
#define SEND_RPL_ENDOFLINKS "365 %s :End of LINKS list\r\n"
// ? "366 <channel> :End of NAMES list"
#define SEND_RPL_ENDOFNAMES "366 %s :End of NAMES list\r\n"
// ? "367 <channel> <banmask>"
#define SEND_RPL_BANLIST "367 %s %s\r\n"
// ? "368 <channel> :End of channel ban list"
#define SEND_RPL_ENDOFBANLIST "368 %s :End of channel ban list\r\n"
// ? "369 <nick> :End of WHOWAS"
#define SEND_RPL_ENDOFWHOWAS "369 %s :End of WHOWAS\r\n"
// ? "371 :<string>"
#define SEND_RPL_INFO "371 :%s\r\n"
// ? "372 :- <text>"
#define SEND_RPL_MOTD "372 :- %s\r\n"
// ? "374 :End of INFO list"
#define SEND_RPL_ENDOFINFO "374 :End of INFO list\r\n"
// ? "375 :- <server> Message of the day - "
#define SEND_RPL_MOTDSTART "375 :- %s Message of the day - \r\n"
// ? "376 :End of MOTD command"
#define SEND_RPL_ENDOFMOTD "376 :End of MOTD command\r\n"
// ? "381 :You are now an IRC operator"
#define SEND_RPL_YOUREOPER "381 :You are now an IRC operator\r\n"
// ? "382 <config file> :Rehashing"
#define SEND_RPL_REHASHING "382 %s :Rehashing\r\n"
// ? "383 You are service <servicename>"
#define SEND_RPL_YOURESERVICE "383 You are service %s\r\n"
// ? "391 <server> :<string showing server's local time>"
#define SEND_RPL_TIME "391 %s :%s\r\n"
// ? "392 :UserID Terminal Host"
#define SEND_RPL_USERSSTART "392 :UserID Terminal Host\r\n"
// ? "393 :<username> <ttyline> <hostname>"
#define SEND_RPL_USERS "393 :%s %s %s\r\n"
// ? "394 :End of users"
#define SEND_RPL_ENDOFUSERS "394 :End of users\r\n"
// ? "395 :Nobody logged in"
#define SEND_RPL_NOUSERS "395 :Nobody logged in\r\n"
// ? "401 <nickname> :No such nick/channel"
#define SEND_ERR_NOSUCHNICK "401 %s :No such nick/channel\r\n"
// ? "402 <server name> :No such server"
#define SEND_ERR_NOSUCHSERVER "402 %s :No such server\r\n"
// ? "403 <channel name> :No such channel"
#define SEND_ERR_NOSUCHCHANNEL "403 %s :No such channel\r\n"
// ? "404 <channel name> :Cannot send to channel"
#define SEND_ERR_CANNOTSENDTOCHAN "404 %s :Cannot send to channel\r\n"
// ? "405 <channel name> :You have joined too many channels"
#define SEND_ERR_TOOMANYCHANNELS "405 %s :You have joined too many channels\r\n"
// ? "406 <nickname> :There was no such nickname"
#define SEND_ERR_WASNOSUCHNICK "406 %s :There was no such nickname\r\n"
// ? "407 <target> :<error code> recipients. <abort message>"
#define SEND_ERR_TOOMANYTARGETS "407 %s :%s recipients. %s\r\n"
// ? "408 <service name> :No such service"
#define SEND_ERR_NOSUCHSERVICE "408 %s :No such service\r\n"
// ? "409 :No origin specified"
#define SEND_ERR_NOORIGIN "409 :No origin specified\r\n"
// ? "411 :No recipient given (<command>)"
#define SEND_ERR_NORECIPIENT "411 :No recipient given (%s)\r\n"
// ? "412 :No text to send"
#define SEND_ERR_NOTEXTTOSEND "412 :No text to send\r\n"
// ? "413 <mask> :No toplevel domain specified"
#define SEND_ERR_NOTOPLEVEL "413 %s :No toplevel domain specified\r\n"
// ? "414 <mask> :Wildcard in toplevel domain"
#define SEND_ERR_WILDTOPLEVEL "414 %s :Wildcard in toplevel domain\r\n"
// ? "415 <mask> :Bad Server/host mask"
#define SEND_ERR_BADMASK "415 %s :Bad Server/host mask\r\n"
// ? "421 <command> :Unknown command"
#define SEND_ERR_UNKNOWNCOMMAND "421 %s :Unknown command\r\n"
// ? "422 :MOTD File is missing"
#define SEND_ERR_NOMOTD "422 :MOTD File is missing\r\n"
// ? "423 <server> :No administrative info available"
#define SEND_ERR_NOADMININFO "423 %s :No administrative info available\r\n"
// ? "424 :File error doing <file op> on <file>"
#define SEND_ERR_FILEERROR "424 :File error doing %s on %s\r\n"
// ? "431 :No nickname given"
#define SEND_ERR_NONICKNAMEGIVEN "431 :No nickname given\r\n"
// ? "432 <nick> :Erroneous nickname"
#define SEND_ERR_ERRONEUSNICKNAME "432 %s :Erroneous nickname\r\n"
// ? "433 <nick> :Nickname is already in use"
#define SEND_ERR_NICKNAMEINUSE "433 %s :Nickname is already in use\r\n"
// ? "436 <nick> :Nickname collision KILL from <user>@<host>"
#define SEND_ERR_NICKCOLLISION "436 %s :Nickname collision KILL from %s@%s\r\n"
// ? "437 <nick/channel> :Nick/channel is temporarily unavailable"
#define SEND_ERR_UNAVAILRESOURCE "437 %s :Nick/channel is temporarily unavailable\r\n"
// ? "441 <nick> <channel> :They aren't on that channel"
#define SEND_ERR_USERNOTINCHANNEL "441 %s %s :They aren't on that channel\r\n"
// ? "442 <channel> :You're not on that channel"
#define SEND_ERR_NOTONCHANNEL "442 %s :You're not on that channel\r\n"
// ? "443 <user> <channel> :is already on channel"
#define SEND_ERR_USERONCHANNEL "443 %s %s :is already on channel\r\n"
// ? "444 <user> :User not logged in"
#define SEND_ERR_NOLOGIN "444 %s :User not logged in\r\n"
// ? "445 :SUMMON has been disabled"
#define SEND_ERR_SUMMONDISABLED "445 :SUMMON has been disabled\r\n"
// ? "446 :USERS has been disabled"
#define SEND_ERR_USERSDISABLED "446 :USERS has been disabled\r\n"
// ? "451 :You have not registered"
#define SEND_ERR_NOTREGISTERED "451 :You have not registered\r\n"
// ? "461 <command> :Not enough parameters"
#define SEND_ERR_NEEDMOREPARAMS "461 %s :Not enough parameters\r\n"
// ? "462 :Unauthorized command (already registered)"
#define SEND_ERR_ALREADYREGISTRED "462 :Unauthorized command (already registered)\r\n"
// ? "463 :Your host isn't among the privileged"
#define SEND_ERR_NOPERMFORHOST "463 :Your host isn't among the privileged\r\n"
// ? "464 :Password incorrect"
#define SEND_ERR_PASSWDMISMATCH "464 :Password incorrect\r\n"
// ? "465 :You are banned from this server"
#define SEND_ERR_YOUREBANNEDCREEP "465 :You are banned from this server\r\n"
// ? "466 :You will be removed from the server"
#define SEND_ERR_YOUWILLBEBANNED "466 :You will be removed from the server\r\n"
// ? "467 <channel> :Channel key already set"
#define SEND_ERR_KEYSET "467 %s :Channel key already set\r\n"
// ? "471 <channel> :Cannot join channel (+l)"
#define SEND_ERR_CHANNELISFULL "471 %s :Cannot join channel (+l)\r\n"
// ? "472 <char> :is unknown mode char to me for <channel>"
#define SEND_ERR_UNKNOWNMODE "472 %s :is unknown mode char to me for %s\r\n"
// ? "473 <channel> :Cannot join channel (+i)"
#define SEND_ERR_INVITEONLYCHAN "473 %s :Cannot join channel (+i)\r\n"
// ? "474 <channel> :Cannot join channel (+b)"
#define SEND_ERR_BANNEDFROMCHAN "474 %s :Cannot join channel (+b)\r\n"
// ? "475 <channel> :Cannot join channel (+k)"
#define SEND_ERR_BADCHANNELKEY "475 %s :Cannot join channel (+k)\r\n"
// ? "476 <channel> :Bad Channel Mask"
#define SEND_ERR_BADCHANMASK "476 %s :Bad Channel Mask\r\n"
// ? "477 <channel> :Channel doesn't support modes"
#define SEND_ERR_NOCHANMODES "477 %s :Channel doesn't support modes\r\n"
// ? "478 <channel> <char> :Channel list is full"
#define SEND_ERR_BANLISTFULL "478 %s %s :Channel list is full\r\n"
// ? "481 :Permission Denied- You're not an IRC operator"
#define SEND_ERR_NOPRIVILEGES "481 :Permission Denied- You're not an IRC operator\r\n"
// ? "482 <channel> :You're not channel operator"
#define SEND_ERR_CHANOPRIVSNEEDED "482 %s :You're not channel operator\r\n"
// ? "483 :You can't kill a server!"
#define SEND_ERR_CANTKILLSERVER "483 :You can't kill a server!\r\n"
// ? "484 :Your connection is restricted!"
#define SEND_ERR_RESTRICTED "484 :Your connection is restricted!\r\n"
// ? "485 :You're not the original channel operator"
#define SEND_ERR_UNIQOPPRIVSNEEDED "485 :You're not the original channel operator\r\n"
// ? "491 :No O-lines for your host"
#define SEND_ERR_NOOPERHOST "491 :No O-lines for your host\r\n"
// ? "501 :Unknown MODE flag"
#define SEND_ERR_UMODEUNKNOWNFLAG "501 :Unknown MODE flag\r\n"
// ? "502 :Cannot change mode for other users"
#define SEND_ERR_USERSDONTMATCH "502 :Cannot change mode for other users\r\n"





class CommandExec {
	private:

	public:
		CommandExec(void);
		~CommandExec(void);

		void	welcome(User* user);
		void	join(User* user, vector<string> args);
		void	part(User* user, vector<string> args);
		void	quit(User* user, vector<string> args);
		void	nick(User* user, vector<string> args);
		void	topic(User *user, vector<string> args);
		void	privmsg(User* user, vector<string> args);
		void	welcome(User* user);
		void	oper(User* user, vector<string> args);
		void	kick(User* user, vector<string> args);
		void	away(User* user, vector<string> args);
		void	names(User* user, vector<string> args);
		// void	mode(User* user, vector<string> args);
		// void	topic(t_params *params, string args, string topic);
		// void	privateMessage(t_params *params, string args, string message);
		// void	oper(string message, t_params* params);
		// void	kick(string message, t_params* params);
		// void	mode(string message, t_params* params);
		// void	user(t_params * params, string args);
};

#endif