#ifndef _REPLY_HPP_
 #define _REPLY_HPP_

#include <iostream>
#include <string>
#include <sys/socket.h>

#include "../Server/Server.hpp"

using namespace std;

// string header_1(Server *server, ssize_t id, string rplyNb);
// string header_2(Server *server, ssize_t id, string rplyNb);

void reply_2(Server* serv, ssize_t uid, int rplyNb, string args, string args2);
void reply(Server* serv, ssize_t uid, int rplyNb, string args);

#define STR_JOIN                    "4545"
#define STR_PART                    "4546"
#define STR_PRVMSG_U                "4547"
#define STR_PRVMSG_C                "4548"
#define STR_NICK                    "4549"
#define STR_USER_R                  "4550"
#define STR_TOPIC                   "4551"
#define STR_RPL_WELCOME				"001"
#define STR_RPL_YOURHOST			"002"
#define STR_RPL_CREATED				"003"
#define STR_RPL_MYINFO				"004"
#define STR_RPL_BOUNCE				"005"
#define STR_RPL_UMODEIS				"221"
#define STR_RPL_AWAY				"301"
#define STR_RPL_UNAWAY				"305"
#define STR_RPL_NOWAWAY				"306"
#define STR_RPL_ENDOFWHO			"315"
#define STR_RPL_LIST				"322" 
#define STR_RPL_LISTEND				"323" 
#define STR_RPL_NOTOPIC				"331" 
#define STR_RPL_TOPIC				"332"
#define STR_RPL_WHOREPLY			"352"
#define STR_RPL_NAMEREPLY			"353"
#define STR_RPL_ENDOFNAMES  		"366"
#define STR_RPL_MOTD		  		"372"
#define STR_RPL_MOTDSTART	  		"375"
#define STR_RPL_ENDOFMOTD	  		"376"
#define STR_RPL_YOUREOPER			"381"
#define STR_RPL_CUSTOMCAP			"4242"
#define STR_RPL_CUSTOMMODESUCCESS	"4243"
#define STR_RPL_CUSTOMHELP      	"4244"
#define STR_RPL_CUSTOMMOTD	     	"4245"
#define STR_ERR_NOSUCHNICK			"401"
#define STR_ERR_NOSUCHCHANNEL		"403"
#define STR_ERR_CANNOTSENDTOCHAN	"404"
#define STR_ERR_TOOMANYCHANNELS		"405" 
#define STR_ERR_TOOMANYTARGETS		"407" 
#define STR_ERR_NORECIPIENT			"411"
#define STR_ERR_NOTEXTTOSEND		"412"
#define STR_ERR_UNKNOWNCOMMAND		"421"
#define STR_ERR_NONICKNAMEGIVEN		"431"
#define STR_ERR_ERRONEUSNICKNAME	"432"
#define STR_ERR_NICKNAMEINUSE		"433"
#define STR_ERR_USERNOTINCHANNEL    "441"
#define STR_ERR_NOTONCHANNEL		"442"
#define STR_ERR_NEEDMOREPARAMS		"461"
#define STR_ERR_ALREADYREGISTERED	"462"
#define STR_ERR_PASSWDMISMATCH  	"464"
#define STR_ERR_CHANNELISFULL		"471"
#define	STR_ERR_INVITEONLYCHAN		"473"
#define STR_ERR_BANNEDFROMCHAN		"474"
#define STR_ERR_BADCHANNELKEY		"475"
#define STR_ERR_BADCHANMASK 		"476"
#define STR_ERR_NOPRIVILEGES	    "481"
#define STR_ERR_CHANOPRIVNEEDED     "482"
#define STR_ERR_RESTRICTED			"484"
#define STR_ERR_NOOPERHOST			"491"
#define STR_ERR_UMODEUNKNOWNFLAG	"501"
#define STR_ERR_USERSDONTMATCH		"502"
#define STR_ERR_USERREALNAMEFORMAT	"4242"
#define STR_JOIN_REPLY								4545
#define STR_PART_REPLY								4546
#define STR_PRVMSG_U_REPLY							4547
#define STR_PRVMSG_C_REPLY							4548
#define STR_NICK_REPLY								4549
#define STR_USER_R_REPLY							4550
#define STR_TOPIC_REPLY								4551
#define STR_RPL_WELCOME_REPLY						1
#define STR_RPL_YOURHOST_REPLY						2
#define STR_RPL_CREATED_REPLY						3
#define STR_RPL_MYINFO_REPLY						4
#define STR_RPL_BOUNCE_REPLY						5
#define STR_RPL_UMODEIS_REPLY						221
#define STR_RPL_AWAY_REPLY							301
#define STR_RPL_UNAWAY_REPLY						305
#define STR_RPL_NOWAWAY_REPLY						306
#define STR_RPL_ENDOFWHO_REPLY						315
#define STR_RPL_LIST_REPLY							322 
#define STR_RPL_LISTEND_REPLY						323 
#define STR_RPL_NOTOPIC_REPLY						331 
#define STR_RPL_TOPIC_REPLY							332
#define STR_RPL_WHOREPLY_REPLY						352
#define STR_RPL_NAMEREPLY_REPLY						353
#define STR_RPL_ENDOFNAMES_REPLY  					366
#define STR_RPL_MOTD_REPLY		  					372
#define STR_RPL_MOTDSTART_REPLY	  					375
#define STR_RPL_ENDOFMOTD_REPLY	  					376
#define STR_RPL_YOUREOPER_REPLY						381
#define STR_RPL_CUSTOMCAP_REPLY						4242
#define STR_RPL_CUSTOMMODESUCCESS_REPLY				4243
#define STR_RPL_CUSTOMHELP_REPLY	  				4244
#define STR_RPL_CUSTOMMOTD_REPLY		 			4245
#define STR_ERR_NOSUCHNICK_REPLY					401
#define STR_ERR_NOSUCHCHANNEL_REPLY					403
#define STR_ERR_CANNOTSENDTOCHAN_REPLY				404
#define STR_ERR_TOOMANYCHANNELS_REPLY				405 
#define STR_ERR_TOOMANYTARGETS_REPLY				407 
#define STR_ERR_NORECIPIENT_REPLY					411
#define STR_ERR_NOTEXTTOSEND_REPLY					412
#define STR_ERR_UNKNOWNCOMMAND_REPLY				421
#define STR_ERR_NONICKNAMEGIVEN_REPLY				431
#define STR_ERR_ERRONEUSNICKNAME_REPLY				432
#define STR_ERR_NICKNAMEINUSE_REPLY					433
#define STR_ERR_USERNOTINCHANNEL_REPLY				441
#define STR_ERR_NOTONCHANNEL_REPLY					442
#define STR_ERR_NEEDMOREPARAMS_REPLY				461
#define STR_ERR_ALREADYREGISTERED_REPLY				462
#define STR_ERR_PASSWDMISMATCH_REPLY  				464
#define STR_ERR_CHANNELISFULL_REPLY					471
#define	STR_ERR_INVITEONLYCHAN_REPLY				473
#define STR_ERR_BANNEDFROMCHAN_REPLY				474
#define STR_ERR_BADCHANNELKEY_REPLY					475
#define STR_ERR_BADCHANMASK_REPLY 					476
#define STR_ERR_NOPRIVILEGES_REPLY					481
#define STR_ERR_CHANOPRIVNEEDED_REPLY				482
#define STR_ERR_RESTRICTED_REPLY					484
#define STR_ERR_NOOPERHOST_REPLY					491
#define STR_ERR_UMODEUNKNOWNFLAG_REPLY				501
#define STR_ERR_USERSDONTMATCH_REPLY				502
#define STR_ERR_USERREALNAMEFORMAT_REPLY			4242
#endif
